{% set name = "pyroma" %}
{% set version = "2.6.1" %}
{% set sha256 = "2527423e3a24ccd56951f3ce1b0ebbcc4fa0518c82fca882e696c78726ab9c2f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: true
  entry_points:
    - pyroma = pyroma:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - docutils

test:
  imports:
    - pyroma

  commands:
    - pyroma --help

about:
  home: https://bitbucket.org/regebro/pyroma
  license: MIT
  license_file: LICENSE.txt
  summary: Test your project's packaging friendliness

extra:
  recipe-maintainers:
    - jakirkham
